export const ELEMENTS = {
  APP_MODAL: 'APP_MODAL',
  APP_MODAL_IMAGE: 'APP_MODAL_IMAGE',
  APP_MODAL_NAME: 'APP_MODAL_NAME',
  APP_MODAL_ACCESS_BUTTON: 'APP_MODAL_ACCESS_BUTTON',
  APP_MODAL_CLOSE: 'APP_MODAL_CLOSE',
};
